services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27018:27017"
        volumes:
            - ./data/db:/data/db
        healthcheck:
          test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
          interval: 10s
          timeout: 3s
          retries: 5
        networks:
            - app-network

    catalog.api:
        image: catalogapi
        build:
          context: ./src
          dockerfile: ./Catalog.Api/Dockerfile
        container_name: catalogapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPassword123
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - ConnectionStrings__CatalogDbConnection=mongodb://mongodb:27017
        ports:
            - "8080:8080"
            - "8081:8081"
        volumes:
            - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
        depends_on:
          mongodb:
            condition: service_healthy
        networks:
            - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local