name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      docker_tag:
        required: true
        type: string
      service_name:
        required: true
        type: string

env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and Push Image
        run: |
          echo "Building image for API: ${{ inputs.docker_tag }}"
          echo "With tag: ${{ env.REGISTRY }}/${{ inputs.service_name }}:${{ inputs.docker_tag }}"
          echo "At Registry: ${{ env.REGISTRY }}/${{ inputs.service_name }}:${{ inputs.docker_tag }}"
          docker build -t ${{ env.REGISTRY }}/${{ inputs.service_name }}:${{ inputs.docker_tag }} -f ./${{ inputs.context}}/${{ inputs.dockerfile }} ./${{ inputs.context}}
          docker push ${{ env.REGISTRY }}/${{ inputs.service_name }}:${{ inputs.docker_tag }}